function param = HB_params()
    param.k_sp = 0.5e-15;                                                   % Single pivot stiffness
    param.K_es = 0.072;                                                     % Extent spring stiffness of the bundle
    param.N_TL = 60;                                                        % Number of tip links 
    param.N_s = 90;                                                         % Number of stereocilia 
    param.K_GS_1 = 145e-3;                                                  % Combined gating-spring stiffness for row 2 LTLD
    param.K_GS_2 = 145e-3;                                                  % Combined gating-spring stiffness for row 3 LTLD
    param.K_SP_1 = param.N_s*param.k_sp/3;                                  % Combined pivot stiffness for row 1
    param.K_SP_2 = param.N_s*param.k_sp/3;                                  % Combined pivot stiffness for row 2
    param.K_SP_3 = param.N_s*param.k_sp/3;                                  % Combined pivot stiffness for row 3
    param.K_ES_1 = 0.05;                                                    % Combined extent spring stiffness for row 1 UTLD
    param.K_ES_2 = 0.025;                                                   % Combined extent spring stiffness for row 2 UTLD
    param.fac = 25; %0.225*9;                          
    param.fac2 = 3;                       
    param.fac3 = 160;                       
    param.lambda_1 = param.fac*6.4516e-19;                                  % Extracellular damping coefficient in the proximity of row 1
    param.lambda_2 = param.fac*6.4516e-19;                                  % Extracellular damping coefficient in the proximity of row 2
    param.lambda_3 = param.fac*6.4516e-19;                                  % Extracellular damping coefficient in the proximity of row 3
    param.lambda_a1 = param.fac2*6e-6;                                      % Intracellular damping coefficient in the proximity of row 1 UTLD
    param.lambda_a2 = param.fac3*6e-6;                                      % Intracellular damping coefficient in the proximity of row 2 UTLD
    param.d1 = 2.77e-9;                                                     % Gating swing for gatiing mechanism at row 2 LTLD
    param.d2 = 2.77e-9;                                                     % Gating swing for gatiing mechanism at row 3 LTLD
    param.T = 300;                                                          % Kelvin scale room temperature
    param.kB = 1.38064852e-23;                                              % Boltzmann constant in S.I. units
    param.Nc = 4;                                                           % Number of transduction channels per tip link
    param.N = param.Nc*param.N_TL/2;                                        % Combined channels at each LTLD
    param.N1 = param.N;                                                     % Combined channels at row 2 LTLD
    param.N2 = param.N;                                                     % Combined channels at row 3 LTLD
    param.z1 = param.K_GS_1*param.d1/param.N1;                              % Single channel gating force at row 2 LTLD
    param.z2 = param.K_GS_2*param.d2/param.N2;                              % Single channel gating force at row 3 LTLD
    param.A1 = 13;                                                          % Parameter that sets resting open probability of row 2 MET channels
    param.A2 = 13;                                                          % Parameter that sets resting open probability of row 3 MET channels
    param.f_max1 = 10e-12/30;               
    param.f_max2 = 40e-12/30;               
    param.Fmax1 = param.f_max1*param.N_TL/2;                                % Combined maximum stall force of row 1 adaptation mechanism
    param.Fmax2 = param.f_max2*param.N_TL/2;                                % Combined maximum stall force of row 2 adaptation mechanism
    param.S = 1;                                                            % Cation feedback strength
    param.l_act1 = param.kB*param.T*log(param.A1)/(param.K_GS_1*param.d1);  % Resting length of first tip link  
    param.l_act2 = param.kB*param.T*log(param.A2)/(param.K_GS_2*param.d2);  % Resting length of second tip link  
    param.singleChannelConductance = 42.0e-12;                              % Single MET channel conductance
    param.gMax = param.Nc*param.N_TL*param.singleChannelConductance/2;        % Combined maximum conductance of the transduction channels at each LTLD 
    param.EP = 0e-3;                                                        % Endocochlear potential
    param.deltaVHBo = -80e-3;                                               % Holding potential of the OHC
    param.K_P = 200e-3;                                                     % Probe stiffness
end